### ISSUE TITLE
How to use `createError` with this setup

### ISSUE THREAD

**Issue by mubaidr** [do4motherOrg/nuxt-trpc-kit#1]
When we use following code to create error in an procedure or query, TRPC always returns status code 500 for the request. 

```ts
throw createError({
  statusCode: 400
})

```

Do we need to use `TRPCError` error every time or is there solution to support nuxt?

**Comment by do4Mother** [comment]
Correct, you should use `TRPCError`. since we have implement trpc inside H3 server

**Comment by mubaidr** [comment]
Cool. But is there any option if I prefer to use create error? Which uses error transformer/ formatter to make it compatible with trpc error?

**Comment by do4Mother** [comment]
the easiest way, is wrap trpc client with useAsyncData

```
<template>
  <h1>{{ error?.message }}</h1>
</template>

<script setup lang="ts">
import type { TRPCClientError } from '@trpc/client';
import type { AppRouter } from '~/server/trpc/routers';

const { $client } = useNuxtApp();
type ErrorOutput = TRPCClientError<AppRouter>
const { data, error, status } = await useAsyncData<{names: string}, ErrorOutput>(() => $client.getNames.query({}), {
  server: false
});
</script>
```

**Comment by do4Mother** [comment]
you can follow from this guideline

https://trpc-nuxt.vercel.app/get-started/tips/composables

**Comment by mubaidr** [comment]
> the easiest way, is wrap trpc client with useAsyncData
> 
> ```
> <template>
>   <h1>{{ error?.message }}</h1>
> </template>
> 
> <script setup lang="ts">
> import type { TRPCClientError } from '@trpc/client';
> import type { AppRouter } from '~/server/trpc/routers';
> 
> const { $client } = useNuxtApp();
> type ErrorOutput = TRPCClientError<AppRouter>
> const { data, error, status } = await useAsyncData<{names: string}, ErrorOutput>(() => $client.getNames.query({}), {
>   server: false
> });
> </script>
> ```

This will just throw 500 error status if error created on server side using createError.

But anyway thanks
